[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x", "openssl"]

[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run prisma generate", "npm run build"]

[start]
cmd = "sh ./entrypoint.sh"